eclipse-ee4j/tyrus

bundles/samples/pom.xml
bundles/samples/src/main/assembly/examples-assembly.xml
bundles/websocket-ri-archive/src/main/assembly/archive.xml
bundles/websocket-risrc-licensee/src/main/assembly/archive.xml
pom.xml
tests/e2e/application-config/pom.xml
tests/e2e/jetty/pom.xml
tests/e2e/standard-config/src/test/java/org/glassfish/tyrus/test/standard_config/ServerSessionConnectToServerTest.java
tests/qa/lifecycle-test/pom.xml

Signed-off-by: Roman Grigoriadi <roman.grigoriadi@oracle.com>

Removed slang message from test, removed obsolete license comment.

---

pom.xml

Signed-off-by: Tomas Kraus <tomas.kraus@oracle.com>

Parent changed to org.eclipse.ee4j:project:1.0.1

---

archetypes/pom.xml

Signed-off-by: Tomas Kraus <tomas.kraus@oracle.com>

GPG plugin updated to 1.6

---

bom/pom.xml

pom.xml in bom still contained javanet parent reference.

Fixed wrong parent reference.

---

pom.xml
samples/shared-collection/pom.xml
tests/e2e/standard-config/pom.xml

EE4J-8 release prepare

---

NOTICE.md

Signed-off-by: Roman Grigoriadi <roman.grigoriadi@oracle.com>

Added notice file.

---

archetypes/pom.xml

maven gpg plugin version update

---

pom.xml

grizzly version update

---

README.md
_config.yml

Signed-off-by: Tomas Kraus <Tomas.Kraus@oracle.com>

Links update.

---

archetypes/echo/pom.xml
client/pom.xml
containers/glassfish/cdi/pom.xml
containers/glassfish/ejb/pom.xml
containers/grizzly-client/pom.xml
containers/grizzly-server/pom.xml
containers/inmemory/pom.xml
containers/jdk-client/pom.xml
containers/servlet/pom.xml
ext/client-cli/pom.xml
ext/client-java8/pom.xml
ext/extension-deflate/pom.xml
ext/monitoring-jmx/pom.xml
pom.xml
samples/auction/pom.xml
samples/cdi/pom.xml
samples/chat/pom.xml
samples/draw/pom.xml
samples/echo-basic-auth/pom.xml
samples/echo-https/pom.xml
samples/echo/pom.xml
samples/programmatic-echo/pom.xml
samples/shared-collection/pom.xml
samples/simplelife/pom.xml
spi/pom.xml

legal files added to target

---

pom.xml

Signed-off-by: Roman Grigoriadi <roman.grigoriadi@oracle.com>

Update checkstyle plugin to 3.0.0

---

etc/config/checkstyle-build.xml
pom.xml
tests/qa/lifecycle-test/pom.xml

Signed-off-by: Roman Grigoriadi <roman.grigoriadi@oracle.com>

Bump jetty-server version, checkstyle version, update checkstyle config.

---

.travis.yml

Build for Travis/CI w/o JavaDocs and deprecated profile

---

core/src/main/java/org/glassfish/tyrus/core/OutputStreamToAsyncBinaryAdapter.java
core/src/main/java/org/glassfish/tyrus/core/ProtocolHandler.java
core/src/main/java/org/glassfish/tyrus/core/TyrusRemoteEndpoint.java
core/src/main/java/org/glassfish/tyrus/core/TyrusWebSocket.java
core/src/main/java/org/glassfish/tyrus/core/WriterToAsyncTextAdapter.java
core/src/test/java/org/glassfish/tyrus/core/TyrusRemoteEndpointTest.java
core/src/test/java/org/glassfish/tyrus/core/WriterInfoTest.java
spi/src/main/java/org/glassfish/tyrus/spi/Writer.java
spi/src/main/java/org/glassfish/tyrus/spi/WriterInfo.java

Enrich Writer by the information for the integration layer

---

_config.yml

Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>

Replace Jakarta Jekyll theme with Eclipse Foundation Jekyll theme

---

pom.xml

Updated depedendencies for 2.x

---

pom.xml

Adopt WebSocket API 2.0.0-RC1

---

client/src/main/java/org/glassfish/tyrus/client/TyrusClientEngine.java
containers/jdk-client/src/main/java/org/glassfish/tyrus/container/jdk/client/HttpResponseParser.java
containers/jdk-client/src/main/java/org/glassfish/tyrus/container/jdk/client/SslFilter.java
containers/jdk-client/src/main/java/org/glassfish/tyrus/container/jdk/client/TransportFilter.java
containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusHttpUpgradeHandler.java
core/src/main/java/org/glassfish/tyrus/core/BinaryBuffer.java
core/src/main/java/org/glassfish/tyrus/core/StrictUtf8.java
core/src/main/java/org/glassfish/tyrus/core/TyrusWebSocketEngine.java
core/src/main/java/org/glassfish/tyrus/core/Utils.java
core/src/main/java/org/glassfish/tyrus/core/frame/CloseFrame.java
core/src/main/java/org/glassfish/tyrus/core/frame/TextFrame.java
core/src/main/java/org/glassfish/tyrus/core/uri/internal/UriComponent.java

Fix the JDK8/JDK11 mixed env for ByteBuffer

---

pom.xml

Updated grizzly version to fix OSGi requirements

---

_config.yml

references for tyrus documentation updated

---

docs/pom.xml

css reference to documentation base

---

bom/pom.xml

bom parent pom fix

---

.travis.yml
pom.xml

Update versions for 2.0.0.RC1 that references e.g. WebSocket 2.0.0 API

---

.gitignore
.travis.yml
etc/config/copyright-exclude
etc/travis/README
etc/travis/travis.sh
pom.xml

Updated dependencies for Tyrus 2.0.0

---

etc/jenkins/Jenkinsfile_ci_build

CI env for Jenkins

---

.gitignore
.travis.yml
pom.xml

Build With JDK 17

---

pom.xml
tests/e2e/standard-config/pom.xml

Updated dependencies

---

.github/workflows/maven.yml
archetypes/echo/src/main/resources/archetype-resources/pom.xml

GitHub actions

---

pom.xml

Parent pom update

---

bom/pom.xml

Update bom/pom.xml parent pom

---

etc/jenkins/Jenkinsfile_ci_build

Signed-off-by: Frederic Gurr <frederic.gurr@eclipse-foundation.org>

Add timeout

---

archetypes/echo/src/main/resources/archetype-resources/pom.xml
bundles/websocket-ri-bundle/pom.xml
client/pom.xml
containers/glassfish/cdi/pom.xml
containers/grizzly-server/pom.xml
containers/servlet/pom.xml
core/pom.xml
ext/client-cli/pom.xml
ext/client-java8/pom.xml
server/pom.xml
tests/containers/jdk-client/src/test/java/org/glassfish/tyrus/container/jdk/client/UnknownHostTest.java
tests/tools/pom.xml

Allow EE10 JAX-B, CDI, and Servlet APIs

---

client/src/main/java/org/glassfish/tyrus/client/SslContextConfigurator.java
client/src/main/java/org/glassfish/tyrus/client/SslEngineConfigurator.java
client/src/main/java/org/glassfish/tyrus/client/ThreadPoolConfig.java
containers/grizzly-client/src/main/java/org/glassfish/tyrus/container/grizzly/client/GrizzlyClientFilter.java
containers/grizzly-server/src/main/java/org/glassfish/tyrus/container/grizzly/server/GrizzlyServerFilter.java
containers/jdk-client/src/main/java/org/glassfish/tyrus/container/jdk/client/SslContextConfigurator.java
containers/jdk-client/src/main/java/org/glassfish/tyrus/container/jdk/client/SslEngineConfigurator.java
core/src/main/java/org/glassfish/tyrus/core/ServiceFinder.java
core/src/main/java/org/glassfish/tyrus/core/uri/internal/MultivaluedHashMap.java

JavaDoc fixes

---

containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusServletContainerInitializer.java
tests/servlet/embedded-glassfish-test/src/main/java/org/glassfish/tyrus/tests/servlet/embedded/DispatchingServletFilter.java

Use Servlet context path for ServerEndpointConfig in upgradeHttpToWebSocket

---

README.md

Separate documentation for Tyrus of versions 1.x and 2.x

---

archetypes/echo/src/main/resources/META-INF/maven/archetype.xml
archetypes/echo/src/main/resources/archetype-resources/pom.xml
archetypes/echo/src/main/resources/archetype-resources/src/main/java/EchoEndpoint.java
archetypes/echo/src/main/resources/archetype-resources/src/main/java/module-info.java
docs/src/main/docbook/getting-started.xml
docs/src/main/docbook/tyrus.ent
pom.xml

Updating archetype and documenting it.

---

client/src/main/java/org/glassfish/tyrus/client/TyrusClientEngine.java
containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusHttpUpgradeHandler.java
core/src/main/java/org/glassfish/tyrus/core/CloseReasons.java
core/src/main/java/org/glassfish/tyrus/core/TyrusWebSocketEngine.java
core/src/main/java/org/glassfish/tyrus/core/frame/CloseFrame.java
core/src/test/java/org/glassfish/tyrus/core/CloseReasonsTest.java

Prevent IAE for close reason phrase > 123 bytes

---

NOTICE.md

Updated legal information for Tyrus bundles

---

bundles/client-jdk/pom.xml
bundles/client/pom.xml
pom.xml

Generate proper javadoc bundles

---

containers/glassfish/cdi/src/main/java/org/glassfish/tyrus/gf/cdi/CdiComponentProvider.java
pom.xml

Updated Jakarta EE 10 versions

---

bundles/client/pom.xml
bundles/websocket-ri-bundle/pom.xml
containers/grizzly-client/pom.xml
containers/grizzly-server/pom.xml
ext/monitoring-jmx/pom.xml
pom.xml

OSGi should allow Grizzly 3 and 4

---

core/src/main/java/org/glassfish/tyrus/core/Handshake.java
pom.xml
tests/e2e/standard-config/pom.xml
tests/e2e/standard-config/src/test/java/org/glassfish/tyrus/test/standard_config/WssApplication.java
tests/e2e/standard-config/src/test/java/org/glassfish/tyrus/test/standard_config/WssOriginTest.java
tests/e2e/standard-config/src/test/java/org/glassfish/tyrus/test/standard_config/springboot/WebSocketConfig.java

Postpone SpringBoot tests until CQ is approved.

---

core/src/main/java/org/glassfish/tyrus/core/TyrusEndpointWrapper.java
core/src/main/java/org/glassfish/tyrus/core/TyrusServerEndpointConfigurator.java
core/src/main/java/org/glassfish/tyrus/core/collection/LazyValue.java
core/src/main/java/org/glassfish/tyrus/core/collection/Value.java
core/src/main/java/org/glassfish/tyrus/core/collection/Values.java

Fix leaking programatic endpoints in the CdiComponentProvider cache.

---

containers/glassfish/cdi/src/main/java/org/glassfish/tyrus/gf/cdi/CdiComponentProvider.java
containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusServletWriter.java
core/src/main/java/org/glassfish/tyrus/core/AnnotatedEndpoint.java
core/src/main/java/org/glassfish/tyrus/core/TyrusEndpointWrapper.java
core/src/main/java/org/glassfish/tyrus/core/TyrusServerEndpointConfigurator.java
core/src/main/java/org/glassfish/tyrus/core/collection/Values.java
core/src/test/java/org/glassfish/tyrus/core/TyrusServerEndpointConfiguratorTest.java

Fix another leaks related to CdiComponentProvider cache

---

README.md

Version 1.19 update

---

server/src/main/java/module-info.java
tests/servlet/embedded-glassfish-test/src/main/java/module-info.java

JPMS related dependency fix

---

README.md

Version 2.0.4 update

---

containers/grizzly-client/src/main/java/org/glassfish/tyrus/container/grizzly/client/GrizzlyClientSocket.java

Fixes #804 
Signed-off-by: Nils Renaud <renaud.nils@gmail.com>

804 revert SslEngineConfigurator support removal in GrizzlyClientSocket

---

README.md

Version 2.1.1/1.20 update

---

pom.xml

Update jakarta dependencies

---

README.md

Version 2.1.2

---

core/src/main/java/org/glassfish/tyrus/core/TyrusEndpointWrapper.java
tests/e2e/standard-config/src/test/java/org/glassfish/tyrus/test/standard_config/userproperties/WSProgramaticUserPropertiesServer.java

Pass UserProperties altered by modifyHandshake to ServerEndpoint#onOpen

---

client/src/main/java/org/glassfish/tyrus/client/ClientManager.java
client/src/main/java/org/glassfish/tyrus/client/TyrusClientEngine.java
client/src/main/java/org/glassfish/tyrus/client/exception/DeploymentHandshakeException.java
client/src/main/java/org/glassfish/tyrus/client/exception/Exceptions.java
client/src/main/java/org/glassfish/tyrus/client/exception/package-info.java
containers/grizzly-client/src/main/java/org/glassfish/tyrus/container/grizzly/client/GrizzlyClientSocket.java
containers/jdk-client/src/main/java/org/glassfish/tyrus/container/jdk/client/JdkClientContainer.java
core/src/main/java/org/glassfish/tyrus/core/collection/SupplierWithEx.java
spi/src/main/java/org/glassfish/tyrus/spi/TyrusClientEndpointConfigurator.java
tests/e2e/standard-config/src/test/java/org/glassfish/tyrus/test/standard_config/HandshakeTest.java

Better Support deployment handshake statuses != 101
Introduce TyrusClientEndpointConfigurator class making UpgradeRequest available before the handshake, not only after it

Better Support deployment handshake statuses != 101

---

client/src/main/java/org/glassfish/tyrus/client/ClientManager.java
core/src/main/java/org/glassfish/tyrus/core/AnnotatedEndpoint.java
core/src/main/java/org/glassfish/tyrus/core/TyrusServerEndpointConfigurator.java
ext/client-java8/pom.xml
pom.xml
tests/release-test/pom.xml
tests/tools/pom.xml

Support JDK 7 again

---

NOTICE.md
archetypes/echo/src/main/resources/archetype-resources/pom.xml
containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusHttpUpgradeHandler.java
pom.xml
tests/servlet/embedded-glassfish-test/pom.xml

Prepare dependencies for Tyrus 2.2.0-M2
